### ISSUE TITLE
AdImage->create() returns deprecated api version warning

### ISSUE THREAD

**Issue by mack-14** [facebook/facebook-php-business-sdk#445] opened 2018-05-19 09:28 UTC
We are using this to create image and get hash from it:

$image = new AdImage(null, $this->parameters['user_account']);
$image->{AdImageFields::FILENAME} = $image;
$image->create();

$image->create() returns "(#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v3.0." I have downloaded the newest stable version of api and I receive this message. If I am doing something wrong?

**Comment by shootingsyh** [comment] 2018-05-21 16:50
@mack-14 can you provide some detail about how did you download the newset stable version? Did you get it from composer?

**Comment by 26adrian26** [comment] 2018-05-28 17:06
Was getting this too, using the parent_id in the constructor is being deprecated. Not sure why the official documentation and examples and still using the method that will be deprecated.

$image = new AdImage();
$image->setParentId(null, $this->parameters['user_account']);
$image->{AdImageFields::FILENAME} = $image;
$image->create();

This worked for me.

**Comment by jingping2015** [comment] 2018-08-13 21:02
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by jingping2015** 2018-08-13 21:02 UTC
