### ISSUE TITLE
Add people to an LTV CustomAudience via the PHP SDK or via curl?

### ISSUE THREAD

**Issue by ryancwalsh** [facebook/facebook-php-business-sdk#342] opened 2017-07-25 22:43 UTC
Is there a way to add people to an LTV CustomAudience via the PHP SDK or via curl?  

I could not find anything about it in the documentation here: https://developers.facebook.com/docs/marketing-api/reference/custom-audience/users/v2.9

But my hunch is that your API can do everything that the website can do, so I'm curious to hear how to add users to an LTV CustomAudience programmatically. 😉

Thanks!

**Comment by ryancwalsh** [comment] 2017-08-14 16:05
This issue could be closed as soon as someone merges my recent [pull request](https://github.com/facebook/facebook-php-ads-sdk/pull/346); I'm not sure what the process is or whom I could ask about it.

I'm getting the sense that this repo has been abandoned, which is really sad. :(

P.S. https://stackoverflow.com/a/45555810/470749 was helpful for me

**Comment by jingping2015** [comment] 2018-08-14 21:13
Hi, it seems like this issue has been open for more than a few months now. We have made many changes in the SDK since then, including releasing a new version. If you can repro your specific issue with the latest version of the SDK, please create a new issue or comment here with further details.

We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by jingping2015** 2018-08-14 21:13 UTC
