### ISSUE TITLE
FacebookAds\Object\AdAccount::createCampaign() undefined

### ISSUE THREAD

**Issue by Virinom** [facebook/facebook-php-business-sdk#462] opened 2018-07-20 01:08 UTC
When i try to use api i get this error.
Call to undefined method FacebookAds\Object\AdAccount::createCampaign()
I searched whole src directory for "createCampaign" function with notepad++ couldn't find any match.
Does this function removed somehow or something is wrong with my composer?

**Comment by jingping2015** [comment] 2018-08-13 22:00
Looks like the function define here : https://github.com/facebook/facebook-php-business-sdk/blob/2673ea6fb41c833d2fda36f6ccab24781a03341e/src/FacebookAds/Object/AdAccount.php#L1351

**Comment by jingping2015** [comment] 2018-08-13 22:00
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed** 2018-08-13 22:00 UTC
