### ISSUE TITLE
Error while creating new campaign 

### ISSUE THREAD

**Issue by ikev61** [facebook/facebook-php-business-sdk#460] opened 2018-07-15 11:08 UTC
first of all, I had to do this
`if(!defined('STDIN'))  define('STDIN',  fopen('php://stdin',  'r'));`
`if(!defined('STDOUT')) define('STDOUT', fopen('php://stdout', 'w'));`
`if(!defined('STDERR')) define('STDERR', fopen('php://stderr', 'w'));`

I got this error while creating a campaign

<b>Fatal error</b>:  Call to undefined method FacebookAds\Object\AdAccount::createCampaign() in <b>C:\xampp\htdocs\myunigram.me\resources\ajax\ajax_ad_api.php</b> on line <b>90</b><br

**Comment by jingping2015** [comment] 2018-08-13 21:58
We've been unable to reproduce this bug, and are unable to investigate further. We are closing the issue for now, if you identify a test case we can use to reproduce your bug feel free to re-open.

**Closed by jingping2015** 2018-08-13 21:58 UTC
